redhat-performance/jetlag

- workload/rwn-workload.py
This commit adds a bandwidth limit impairment. The limit is specified as an integer in kilobits.
I changed the way the "Applying impairments" message works to make it more friendly to adding more impairments.
I don't have the cluster needed to test this, so only parts are tested. I tested the new message, and running the script to make sure the parts before kube-burner are working. I also tested the command applied manually on my computer instead of through this script.
```
>>> apply_latency_packet_loss(None, None, None, 0, 0, 0)
Invalid state. Applying no impairments.
>>> apply_latency_packet_loss(None, None, None, 0, 0, 1)
Applying only bandwidth limit impairment
>>> apply_latency_packet_loss(None, None, None, 0, 1, 0)
Applying only packet loss impairment
>>> …
```
> Bandwidth limit

- README.md
- ansible/roles/sno-create-ai-cluster/tasks/main.yml
AI v1.0.20.3 seems not picking the machine network CIDR from the list, so included this patch request to update that CIDR config post cluster creation.
> update machine network cidr for sno deploy

- ansible/roles/bastion-network/templates/jetlag.conf.j2
- ansible/roles/bastion-network/templates/resolv.conf.j2
Included dnsmasq configuration to resolve ingress routes for SNO, 
Tested on public routable VLAN env.
> dns resoln for sno ingress routes

- ansible/disconnected-sync-ocp-release.yml
- ansible/roles/bastion-disconnected-registry/tasks/main.yml
- ansible/roles/bastion-ocp-version/tasks/main.yml
- ansible/roles/disconnected-sync-ocp-release/defaults/main/bastion-disconnected-registry.yml
- ansible/roles/disconnected-sync-ocp-release/defaults/main/main.yml
- ansible/roles/disconnected-sync-ocp-release/tasks/main.yml
- ansible/setup-bastion.yml
- ansible/vars/.gitignore
- ansible/vars/disconnected-sync-ocp-release.sample.yml
quick SNO testing of different versions
> Allow syncing of separate ocp releases to the bastion machine for

- ansible/roles/bastion-ocp-version/tasks/main.yml
- ansible/roles/boot-iso/tasks/supermicro.yml
- docs/troubleshooting.md
Changes:
1. Copies the pull secret to the bastion. This is necessary as the current design expects the pull secret to be there, but it isn't automated.
2. Added ignore_errors to the "SuperMicro - Set Boot" command. This is needed to run JetLag on clusters that have machines whose BMC firmware version is too old.
3. Added troubleshooting documentation for the error expected in change 2, and the error that requires resetting the machine.
> Fix deploy issues

- ansible/bm-deploy.yml
- ansible/inventory/inventory-bm.sample
- ansible/inventory/inventory-rwn.sample
- ansible/inventory/inventory-sno.sample
- ansible/roles/bastion-network/templates/jetlag.conf.j2
- ansible/roles/boot-iso/tasks/main.yml
- ansible/roles/create-inventory/tasks/main.yml
- ansible/roles/create-inventory/templates/inventory-bm.j2
- ansible/roles/create-inventory/templates/inventory-rwn.j2
- ansible/roles/create-inventory/templates/inventory-sno.j2
- ansible/roles/sno-create-ai-cluster/tasks/main.yml
- ansible/roles/sno-generate-discovery-iso/tasks/10_custom_iso.yml
- ansible/roles/sno-generate-discovery-iso/tasks/main.yml
- ansible/roles/validate-vars/tasks/main.yml
- ansible/rwn-deploy.yml
- ansible/sno-deploy.yml
- ansible/vars/all.sample.yml
This helps deploy only on subset of hosts in the allocation.
Also introduces additional checks to ensure that requested
worker/sno nodes can be accomodated in the lab allocation.
If `worker_node_count` or `sno_node_count` are empty, we deploy
on all avaialable nodes after accounting for bastion and controlplane.
This also helps enforce the usage of `worker_node_count` in tasks where
it was previously not used.
> Introduce `sno_node_count` variable

- ansible/roles/bastion-assisted-installer/tasks/main.yml
- ansible/roles/bastion-disconnected-registry/tasks/main.yml
- ansible/roles/bastion-http/tasks/main.yml
One example would be if you reboot the bastion, you could simply
rerun the setup-bastion playbook and the pods will be restarted
for you.
> Ensure pods are started if rerunning the setup-bastion playbook

- ansible/roles/bm-post-cluster-install/templates/localstorage.yml.j2
It actually seems to work regardless anyhow, but lets be accurate.
> No longer limit localstorage operator to install from 4.7 channel

- README.md
- docs/deploy-bm-ibmcloud.md
- docs/deploy-sno-ibmcloud.md
- docs/order-hardware-ibmcloud.md
1. Added a doc for IBM cloud hardware ordering procedure
2. Formatted the file to make it more comprehensible
3. Added references to this file inside of relevant docs (README.md, docs/deploy-bm-ibmcloud.md and docs/deploy-sno-ibmcloud.md)
> added and formatted doc for ordering ibmcloud hardware

- ansible/roles/bastion-ocp-version/tasks/bash-completion.yml
- ansible/roles/bastion-ocp-version/tasks/main.yml
It's way more convenient to work with oc using
bash completion.
Signed-off-by: Alexander Chuzhoy <achuzhoy@redhat.com>
> Add bash completion for oc

- README.md
- ansible/roles/install-cluster/tasks/check-cluster-install.yml
1. Added Lenovo fix boot order task in check-cluster-install.yml (ansible/roles/install-cluster/tasks/check-cluster-install.yml)
2. README.md updated to include Lenovo BM devices in the list of tested hardware on IBM Cloud
> ibmcloud BM lenovo fix boot order

- ansible/roles/create-ai-cluster/templates/99-master-workload-partitioning.yml
- ansible/roles/create-ai-cluster/templates/crio-runtime-workload-management.conf.j2
- ansible/roles/create-ai-cluster/templates/kubernetes-workload-pinning.j2
- ansible/roles/ibmcloud-sno-create-ai-cluster/defaults/main/main.yml
- ansible/roles/ibmcloud-sno-create-ai-cluster/tasks/01_manifest_task.yml
- ansible/roles/sno-create-ai-cluster/defaults/main/main.yml
- ansible/roles/sno-create-ai-cluster/tasks/01_manifest_task.yml
- ansible/roles/validate-vars/tasks/main.yml
- docs/tips-and-vars.md
Added workload-pinning-manifests to be included during SNO installs.
Modified tips-and-vars.md to include explanation for reserved_cpus var settings.
> add reserved_cpus for workload pinning on SNOs

- README.md
- ansible/create-inventory.yml
- ansible/roles/bastion-install/tasks/main.yml
- ansible/roles/create-inventory/tasks/find_supermicro.yml
- ansible/roles/create-inventory/tasks/main.yml
- ansible/roles/create-inventory/templates/inventory-bm.j2
- ansible/roles/install-early-deps/tasks/main.yml
- ansible/setup-bastion.yml
After installing ansible on the machine that will run jetlag playbooks, the user doesn't need to install anything else manually.
The system packages, pip packages and ansible galaxy packages are all handled by the playbooks as necessary.
Additionally we check to see if we need to deal with the Supermicro tools based on presence of the nodes.
I've only changed the baremetal inventory template at this point.
> Make getting started more user friendly

- ansible/roles/bm-post-cluster-install/defaults/main/main.yml
- ansible/roles/bm-post-cluster-install/tasks/main.yml
- ansible/roles/bm-post-cluster-install/templates/performance-addon-operator.yml.j2
- ansible/vars/lab.yml
- docs/tips-and-vars.md
1. Added pao install tasks for standard BM cluster 
2. Made changes to cpu reserve tips in the tips-and-vars doc
3. Corrected the quads url for the ALIAS lab in lab.yml
Haven't been able to test due to cluster install issues in the ALIAS lab but these are basically the same tasks that were previously tested on SNOs
> pao install tasks on standard bm cluster and changes in tips doc

- ansible/roles/disconnected-sync-acm-d/tasks/main.yml
- ansible/vars/disconnected-sync-acm-d.sample.yml
> ACM 2.5 mirror mapping now includes MCE images, so removing syncing MCE

- ansible/roles/bastion-install/defaults/main.yml
- ansible/roles/bastion-install/tasks/main.yml
This installs promdump so that a prometheus data store archive can be created after tests are run.
> adding promdump to bastion server

- README.md
- ansible/roles/validate-vars/tasks/main.yml
- docs/deploy-bm-ibmcloud.md
- docs/deploy-bm-quickstart.md
- docs/order-hardware-ibmcloud.md
- docs/troubleshooting.md
TLDR;
* Change reference from RHEL8.4 to RHEL8.6 for internal/lab/repo reasons
* Change reference from CentOS to Rocky
This is a doc patch to remove references to RHEL8.4 and instead
encourage usage of RHEL8.6.
Internally our globalsync repos do not have ansible-core* packages
present for 8.4, however these are present for 8.6 in the AppStream
repositories.
(If someone uses an RHN subscription this is a non-issue)
This means that people using a Scale Lab (or ALIAS) provided internal
repository will have dependency issues with Ansible provided via RPM.
(This issue was raised by @yobshans).
```
TASK [bastion-install : Install ansible] ************************************************************************************************************************************
Wednesday 08 June 2022 …
```
> doc: prefer RHEL8.6 as a base, swap Rocky for CentOS

- ansible/roles/create-inventory/defaults/main/dns.yml
`bastion_dnsmasq_cd_network_offset` will end up undefined if we do not link dns.yml into the create-inventory role.
> Fix issue when creating inventory with hypervisors on undefined var.

- ansible/roles/bastion-disconnected-registry/tasks/main.yml
- docs/tips-and-vars.md
Description -
In a disconnect cluster deployment, a common usage pattern would be to mirror objects to the disconnect registry for container deployments. Therefore deleting images from the registry is also needed. Currently, the disconnect registry does not allow deletions.
Solution: enable the "REGISTRY_STORAGE_DELETE_ENABLED" flag at the registry creation task.
Unit-test: I have tested it on my disconnected IPv6 cluster
> Add REGISTRY_STORAGE_DELETE_ENABLED flag to the disconnect registry

- ansible/roles/bastion-install/tasks/main.yml
- ansible/roles/create-inventory/templates/inventory-rwn.j2
- ansible/roles/create-inventory/templates/inventory-sno.j2
and SNOs.  Also conservatively set `supermicro_nodes` to default to true
for ibmcloud environments.
> Fix AnsibleUndefinedVariable for `supermicro_nodes` for rh lab with RWN

- docs/deploy-bm-ibmcloud.md
- docs/deploy-bm-quickstart.md
Add the following documentation updates:
1. deploy-bm-quickstart.md - mention using bootstrap.sh for ansible version
2. deploy-bm-quickstart.md - mention admin permissions requirement in ibmcloud
3. deploy-bm-ibmcloud.md - mention and show how to assign specific hardware when ibmcloud account is shared and default hardware picking for create-inventory is incorrect to `ansible/vars/ibmcloud.yml`
4. deploy-bm-ibmcloud.md - add how to update custom master/worker names
5. deploy-bm-ibmcloud.md - Add supermicro_nodes=True to the [all:vars] if getting error: "Check if SMCIPMITool tar is downloaded"
> update ibm cloud documentation

- ansible/roles/create-ai-cluster/tasks/main.yml
- ansible/roles/create-ai-cluster/templates/99-disconnected-dns-workaround.yml
- ansible/roles/create-ai-cluster/templates/disconnected-dns-hosts
queries from coredns due to alertmanager configuration
> DNS workaround until dns issue is resolved regarding forwarded "ANY"

- ansible/roles/bastion-install/defaults/main.yml
- ansible/roles/sno-create-ai-cluster/tasks/01_manifest_task.yml
- ansible/roles/sno-post-cluster-install/tasks/main.yml
- ansible/roles/sno-post-cluster-install/templates/performance-profile.yml.j2
- ansible/roles/validate-vars/tasks/main.yml
- docs/tips-and-vars.md
1. Removed dependencies on "install_performance_addon_operator" for DU profile setup on OCP 4.11 or higher
2. Updated Kube-burner url to latest version
3. Updated performance-profile based on cnf-feature-deploy repo
4. Updated the "tips and vars" doc to reflect the changes
> Removed PAO install for SNO DU-profile on OCP 4.11 and higher

- ansible/roles/wait-hosts-discovered/defaults/main/main.yml
- ansible/roles/wait-hosts-discovered/tasks/main.yml
- ansible/roles/wait-hosts-discovered/tasks/set_node_install_disk.yml
> Allow setting worker node disks separately from control-plane node disks

- ansible/roles/sno-post-cluster-install/tasks/main.yml
This was an oversight in the last du-profile related commit.
> folder correction for perf-profile placement

- ansible/roles/generate-discovery-iso/tasks/main.yml
- Ansible uri moduel has a default timeout of 30 seconds 
- Ansible get_url module has a default timeout of 10 seconds
On a medium sized cluster, the `get_url` module was bumping into the default timeout. From the error message, it made it seem like a networking issue, however the client was terminating the connection.
Instead of having two different timeouts I am recommending we default to a single 60 second timeout for these tasks.
Signed-off-by: Joe Talerico <jtaleric@redhat.com>
> Update the default timeout

- ansible/roles/sno-wait-hosts-discovered/tasks/main.yml
Correctly sets hostname for disconnected ipv6 sno clusters (probably missed in [#288](https://github.com/redhat-performance/jetlag/pull/288))
> set proper hostname for disconnected ipv6 sno

- ansible/roles/sno-post-cluster-install/tasks/main.yml
- ansible/roles/sno-post-cluster-install/templates/performance-addon-operator.yml.j2
Disable default OperatorHub sources and apply olm-mirror ICSP and CatalogSource on disconnected SNO clusters
> disconnected sno post install operator sync

- ansible/roles/disconnected-sync-operator-index/templates/operator-index.Dockerfile.j2
have changed in the base ose-operator-registry image to make v4.11 behave like v4.12
> Since the last time I have synced a v4.11 operator index, something must

- ansible/roles/sno-install-cluster/templates/install-config-overrides.yml.j2
- ansible/roles/sno-post-cluster-install/defaults/main.yml
- ansible/roles/sno-post-cluster-install/tasks/main.yml
- ansible/roles/sno-post-cluster-install/templates/ReduceMonitoringFootprint.yaml
- ansible/roles/sno-post-cluster-install/templates/performance-profile.yml.j2
- docs/tips-and-vars.md
1. Added install config overrides for composable openshift when du_profile is enabled on ocp 4.13
2. Add ReduceMonitoringFootprint.yaml CR to sno_post_cluster_install tasks for du_profile
3. Modified machine config pool watch tasks post applying performance profile and tuned patch to accommodate config update behaviors observed with composable openshift in du_profile in ocp 4.13
4. Updated doc
> Add composable openshift feature to du_profile for OCP 4.13

- ansible/vars/all.sample.yml
if rwn_lab_interface and rwn_network_interface are commented, then bm-deploy will fail.  Add comments in all.sample.yml to document that the variables should not be commented.
Fixes: https://github.com/redhat-performance/jetlag/issues/331
> Fix issue with bm-deploy failing

- ansible/roles/bastion-http/tasks/main.yml
Fails to pull image quay.io/repository/centos7/httpd-24-centos7  - seems `repository` in URL is not necessary. 
``` 
TASK [bastion-http : Create http container in http pod] *****************************************************************************************************************************************************************************
fatal: [e39-h05-000-r650.rdu2.scalelab.redhat.com]: FAILED! => {"changed": false, "msg": "Can't pull image quay.io/repository/centos7/httpd-24-centos7", "stderr": 
"Trying to pull quay.io/repository/centos7/httpd-24-centos7:latest...\nError: initializing source docker://quay.io/repository/centos7/httpd-24-centos7:latest: 
reading manifest latest in quay.io/repository/centos7/httpd-24-centos7: unauthorized: access to the requested resource is not …
```
> Fails to pull image quay.io/repository/centos7/httpd-24-centos7 - wrong url?

- .gitignore
- README.md
Documentation fix:
- Adding ibmcloud sl plugin installation prerequisites to readme doc.
required when running: 
`$ ansible-playbook ansible/ibmcloud-create-inventory.yml`
- Adding .idea/ to gitingnore when using JetBrains PyCharm
> update ibmcloud sl plugin 

- ansible/roles/bastion-install/tasks/main.yml
- removing duplicate openshift-client download
- replacing removed opm-linux download
> fix for 2960e64 opm/openshift-client

- ansible/roles/sno-wait-hosts-discovered/tasks/main.yml
This change is required to set the hostname correctly.  Otherwise it's set to master-0, which is not the actual hostname of the cluster to be installed, and this error results:
```
TASK [sno-wait-hosts-discovered : Adjust non-by-path selected install disk] ***********************************************************************************************************************
task path: /home/rkrawitz/sandbox/JetLag/ansible/roles/sno-wait-hosts-discovered/tasks/set_install_disk.yml:22
Monday 20 November 2023  12:02:57 -0500 (0:00:00.103)       0:21:00.436 ******* 
fatal: [installhost.example.com]: FAILED! => {"msg": "The conditional check 'current_install_disk != hostvars[sno_hostname].install_disk' failed. The error was: error while evaluating conditional (current_install_disk != …
```
> Fix SNO installer for 4.14.  The hostname needs to be set unconditionally

- ansible/roles/hv-coredns/tasks/main.yml
mistakenly detects port 53 in use from the previous running coredns.
> Have coredns restart automatically. Sometimes coredns starts so fast it

- ansible/roles/bastion-ocp-version/tasks/main.yml
Check for `rhel_version` and add it to the oc client tarball extract.
The check looks to see if the kernel version starts with a 4 vs 5.
I have not tested against < 4.15 -- not sure if the entire build process has changed.
Fixes #444
> Fix issue 444

- ansible/roles/bastion-install/tasks/main.yml
- ansible/roles/bastion-ocp-version/tasks/main.yml
- ansible/roles/validate-vars/tasks/main.yml
rhel version since the create-inventory playbook which runs before a bastion machine is selected includes the validate vars role
> Turns out validate vars is not the best place to determine the bastion

- ansible/roles/create-inventory/tasks/main.yml
- ansible/vars/lab.yml
- While r750 are more of a storage class machine they can be used as a substitute for an r650
- Proc and Memory specs on these two machine types are the same
- r750s have 4 1.5T nvme so they can do 2nd disk like the r650s
- Only caveat is if doing ACM precaching for upgrades, you'll need to pair two of the r750s nvme drives together to present 3T of space to match the r650s
> setup r750 configs to match the r650s

- ansible/roles/bastion-assisted-installer/defaults/main/main.yml
- ansible/roles/create-ai-cluster/tasks/main.yml
- ansible/roles/wait-hosts-discovered/tasks/main.yml
I'm open to suggestions about the assisted-installer version(s). I was unable to locate any definitive release/support version information, which is a bit frustrating. Previously the UI container was versioned differently: although I'm using the same version currently for both, I created two separate vars to allow each to be set separately if desired.
Updating beyond v2.29 required a change in the cluster JSON payload from `api_vip` as a string to `api_vips` as a list of objects containing an `"id"` field. While the current workflow passes a network interface name to create the cluster, we don't have an IP as this point and the field is not required: I simply dropped `api_vip` and `ingress_vip` from the "Create cluster" step and constructed the proper object list for the "Patch cluster …
> Update JetLag's assisted-installer version

- ansible/roles/sno-post-cluster-install/tasks/main.yml
- ansible/roles/sno-post-cluster-install/templates/openshift-marketplace-ns.yaml
1. Added a template for openshift-marketplace ns with correct annotations for vDUs corresponding to https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/source-crs/extra-manifest/09-openshift-marketplace-ns.yaml
2. Updated post install tasks to create openshift-markeplace ns and annotate CatalogSource accordingly for DUs
> Annotate openshift-marketplace ns and catalogSource for DUs

- docs/bastion-deploy-bm-byol.md
The Bring Your Own Lab documentation incorrectly documents the variable `controlplane_network_interface`. This variable is only referenced in the `create-inventory` template files, which aren't used in BYOL as the inventory file is constructed manually.
Resolves #428
> Remove `controlplane_network_interface` from BYOL documentation

- ansible/roles/bastion-install/defaults/main.yml
- ansible/roles/bastion-install/tasks/main.yml
`rh_crucible_url` is using a boiler plate URL.
This work depends on the `rh_crucible_url` pointing to AndrewT's crucible gitlab repo.
Closes #465
> Adding Crucible install on the bastion

- README.md
- ansible/vars/all.sample.yml
- ansible/vars/ibmcloud.sample.yml
- docs/bastion-deploy-bm-byol.md
- docs/bastion-deploy-bm.md
- docs/deploy-bm-ibmcloud.md
- docs/deploy-sno-ibmcloud.md
- docs/deploy-sno-quickstart.md
- docs/hypervisors.md
- docs/order-hardware-ibmcloud.md
- docs/tips-and-vars.md
- docs/troubleshooting.md
Rework all startup documents to encourage installing and running Jetlag on the cluster bastion node.
I generally tried to improve consistency between the various guides, creating a "reusable" bastion setup section that's copied into each (which involved shifting some unique segments). My goal was to retain the basic concept of a "single page" quickstart for each platform while helping to avoid drift between the various documents by isolating the bastion setup into a "chunk". (If only GitHub Markdown had an "embed markdown file here".)
PANDA-329
Resolves #440
> Adjust all guides for usage from bastion

- ansible/roles/hv-install/tasks/main.yml
- ansible/roles/hv-network/tasks/main.yml
- ansible/roles/hv-vm-create/templates/kvm-def.xml.j2
I have not tested this with RHEL8 HVs yet.
I have deployed SNOs on RHEL9 HVs using this patch.
> support for handling RHEL9 hv node setup

- ansible/roles/bastion-install/tasks/main.yml
Get `oc` and `kubectl` binaries from `openshift-client-linux-amd64-rhel8.tar.gz` as the default `openshift-client-linux.tar.gz` versions are now built with RHEL 9 libc and don't run on RHEL 8.
Resolves #505
> Fix RHEL 8 bastion setup

- ansible/roles/bastion-install/tasks/main.yml
Without `force: true` the bastion setup will fail if a previous setup-bastion installed crucible.
> Force git to always pull crucible even if the directory exists

- ansible/bm-deploy.yml
- ansible/ibmcloud-bm-deploy.yml
- ansible/ibmcloud-setup-bastion.yml
- ansible/ibmcloud-sno-deploy.yml
- ansible/roles/bastion-install/defaults/main.yml
- ansible/roles/bastion-install/tasks/main.yml
- ansible/roles/bastion-ocp-version/tasks/main.yml
- ansible/roles/ocp-release/defaults/main.yml
- ansible/roles/ocp-release/tasks/main.yml
- ansible/roles/sync-ocp-release/tasks/main.yml
- ansible/roles/validate-vars/defaults/main.yml
- ansible/roles/validate-vars/tasks/main.yml
- ansible/rwn-deploy.yml
- ansible/setup-bastion.yml
- ansible/sno-deploy.yml
- ansible/sync-ocp-release.yml
- ansible/vars/all.sample.yml
- ansible/vars/ibmcloud.sample.yml
- ansible/vars/sync-ocp-release.sample.yml
- docs/bastion-deploy-bm-byol.md
- docs/bastion-deploy-bm.md
- docs/deploy-bm-ibmcloud.md
- docs/deploy-sno-ibmcloud.md
- docs/deploy-sno-quickstart.md
- docs/tips-and-vars.md
This removes the need to explicitly define the OCP release image and instead requires `ocp_version` and `ocp_build` from the user. OpenShift version could be specific like 4.15.4 or more generic like latest-4.15. The build should denote whether the required OCP version is ga or under development using the keys `ga` or `dev`. This commit also removes the circular dependency on having oc (installed as `oc.latest` to extract the ocp client/installer binaries). Overall, this greatly simplifies the use of jetlag while at the same time making it intelligent to deploy latest ga/nightly versions across minor releases.
Co-authored-by: Alex Krzos <akrzos@redhat.com>
Closes: https://github.com/redhat-performance/jetlag/issues/501
> Allow specifying of OpenShift stream for install, closes #501

- ansible/roles/validate-vars/tasks/main.yml
Now that the discovery of `openshift_version` is done dynamically in `ocp_release`, the attempt to validate DU setup based on OpenShift version is doomed to failure. Remove the validation rather than go to great lengths to repair a validation specific to OpenShift 4.9 and 4.10.
> Remove problematic validation

- ansible/bm-deploy.yml
- ansible/ibmcloud-bm-deploy.yml
- ansible/ibmcloud-sno-deploy.yml
- ansible/roles/install-cluster/tasks/main.yml
- ansible/rwn-deploy.yml
- ansible/sno-deploy.yml
The new `configure-local-storage` role was called indirectly from `install-cluster`, but calling it directly from the playbooks will make it more visible and maintainable.
> "Promote" configure-local-storage references

- ansible/vars/lab.yml
The ALIAS lab (aka performance lab) has moved from BOS to RDU3, so adjust the addresses.
Resolves #517
> Update ALIAS (perfscale) lab settings

- ansible/roles/bastion-install/tasks/main.yml
The output of the OpenSSH private key in the **bastion-install : Copy ssh keys to bastion** task is making the logs unavailable in Prow, they get removed because of sensitive information:
```
This file contained potentially sensitive information and has been removed.
```
> Dont log ssh keys

- ansible/inventory/inventory-sno.sample
- ansible/roles/bastion-dnsmasq/templates/jetlag.conf.j2
- ansible/roles/create-inventory/templates/inventory-sno.j2
- ansible/roles/hv-dnsmasq/templates/jetlag.conf.j2
- ansible/roles/sno-create-ai-cluster/tasks/main.yml
- ansible/roles/sno-create-ai-cluster/templates/nmstate.yml.j2
- docs/deploy-sno-quickstart.md
This change improves consistency between the SNO and BM inventory.
Resolves #239
> Use `ip` instead of `ip-address` in SNO inventory

- ansible/roles/create-inventory/tasks/main.yml
Quads was updated to 2.0, this updates the default url to get ocpinventory from /cloud/cloudxx_ocpinventory to
/instack/cloudxx_ocpinventory
SSL was also enabled and has been added to the default url
> Update default QUADs url

- ansible/roles/create-inventory/defaults/main/networks.yml
- ansible/roles/create-inventory/templates/inventory-sno.j2
- ansible/roles/sno-post-cluster-install/defaults/main/main.yml
- ansible/roles/sno-post-cluster-install/defaults/main/storage.yml
- ansible/roles/sno-post-cluster-install/tasks/main.yml
- ansible/roles/sno-post-cluster-install/templates/localstorage.yml.j2
- ansible/roles/sno-post-cluster-install/templates/localvolume.yml.j2
- ansible/roles/sno-post-cluster-install/templates/localvolume2.yml.j2
- ansible/roles/sno-post-cluster-install/templates/metal3.yml
- ansible/roles/sno-post-cluster-install/templates/minio.yml.j2
- ansible/roles/sno-post-cluster-install/templates/openshift-gitops-operator.yml.j2
Clustertype: SNO did not include the components necessary to be able to install ACM.
This patch adds components so that the ztp and hub deploy scripts in acm-deploy-load should be able to be run on a cluster_type: SNO deployment done by jetlag.
> Add components for ACM to install on SNO clusters

- ansible/roles/create-inventory/tasks/main.yml
- ansible/roles/create-inventory/templates/inventory-mno.j2
- ansible/vars/all.sample.yml
- ansible/vars/lab.yml
- docs/deploy-mno-performancelab.md
- docs/deploy-mno-scalelab.md
Adding some improvements to deploy in public VLANs in bm. Also updating the docs accordigly
> [PERFSCALE-3427] Public VLAN improvements

- ansible/roles/create-inventory/templates/inventory-mno.j2
This variable needs to be set at the inventory level (rather than using the default value) when public_vlan is enabled.
> Add controlplane_network to inventory

- ansible/roles/hv-vm-manifests-standard/templates/siteconfig.yml.j2
adding role=master or role=worker to an hv_vm inventory definition will assign that node to they specified role when the siteconfig is built
> allow role overrides for VMs in standard clusters

- bootstrap.sh
Let's make bootstrap a little less verbose
Related #579
> Quieter bootstrap

- ansible/roles/sync-acm-d/tasks/main.yml
- ansible/vars/sync-acm-d.sample.yml
> Remove Deprecated container image

- README.md
- ansible/mno-deploy.yml
- ansible/roles/boot-iso/tasks/libvirt.yml
- ansible/roles/boot-iso/tasks/main.yml
- ansible/roles/create-ai-cluster/defaults/main/main.yml
- ansible/roles/create-ai-cluster/tasks/main.yml
- ansible/roles/create-ai-cluster/templates/mac_interface_map.json.j2
- ansible/roles/create-inventory/defaults/main/main.yml
- ansible/roles/create-inventory/templates/inventory-mno.j2
- ansible/roles/mno-post-cluster-install/defaults/main/main.yml
Baremetal control plane and virtual workers.
I think this will also do baremetal control plane and workers and virtual workers.
> Hybrid deployments

- ansible/roles/create-ai-cluster/defaults/main/main.yml
- ansible/roles/mno-post-cluster-install/defaults/main/main.yml
- These roles don't use the variable so it doesn't need to be in their defaults.
> Removing hybrid_worker_count from non-create inventory roles

- ansible/mno-scale-out.yml
- ansible/roles/boot-iso/defaults/main.yml
- ansible/roles/boot-iso/tasks/dell.yml
- ansible/roles/boot-iso/tasks/hp.yml
- ansible/roles/boot-iso/tasks/lenovo.yml
- ansible/roles/boot-iso/tasks/libvirt.yml
- ansible/roles/boot-iso/tasks/main.yml
- ansible/roles/boot-iso/tasks/supermicro.yml
- ansible/roles/mno-scale-out-csr/defaults/main.yml
- ansible/roles/mno-scale-out-csr/tasks/check_nodes_joined.yml
- ansible/roles/mno-scale-out-csr/tasks/main.yml
- ansible/roles/mno-scale-out/defaults/main.yml
- ansible/roles/mno-scale-out/tasks/main.yml
- ansible/roles/mno-scale-out/templates/nodes-config.yml.j2
- ansible/vars/scale_out.sample.yml
- docs/scale-out-mno.md
- Add nodes to worker inventory section and update vars in scaleout.yml to add nodes to the existing cluster.
- https://docs.openshift.com/container-platform/4.17/nodes/nodes/nodes-nodes-adding-node-iso.html
> Adding Scale Out functionality

- ansible/roles/create-inventory/tasks/main.yml
- docs/tips-and-vars.md
providing an absolute path to ocpinventory json file for modified inventory data
> Support local ocp inventory file in override

- docs/troubleshooting.md
I encountered a BMC DNS server issue that caused a failure to read Virtual Media, so I added it to the Troubleshooting section.
> Troubleshooting BMC DNS server issue

- ansible/roles/bastion-ocp-version/tasks/main.yml
The missing config path caused the OpenShift installer download to fail.
Adding the full path using -`-to {{ ocp_version_path }} --registry-config /root/.docker/config.json` resolved the issue.
[IBM Cloud CI installation failed](https://github.com/redhat-performance/benchmark-runner/actions/runs/15894569776/job/44823330911) due to this issue
> Add missing config path

- ansible/vars/lab.yml
This is required for testing the hybrid workers scenario on the metal-perfscale-cpt cluster(cloud31).
> Add r760 performancelab hw_vm_counts vars

- ansible/roles/create-inventory/templates/inventory-mno.j2
- ansible/vars/lab.yml
This is a follow up to https://github.com/redhat-performance/jetlag/pull/671 to allow testing the hybrid workers scenario on the metal-perfscale-cpt cluster(cloud31).
> Extend inventory template for performancelab hypervisors and hw_nic_name

- ansible/mno-scale-out.yml
The `mno-scale-out.yml` playbook is failing because the `DELL - Insert Virtual Media task `cannot find the `rh_labs` variable. After some investigation, I discovered that `rh_labs` is correctly defined in `ansible/vars/lab.yml`. To make this variable available to the playbook, We need to add a reference to `vars/lab.yml `within the vars block of the `ansible/mno-scale-out.yml `playbook.
> Added missing lab variables to MNO (Multi Node Openshift) scale out deployment

- ansible/roles/wait-hosts-discovered/tasks/main.yml
We've observed the following failure in the `Wait up to 40 min for nodes to be discovered` which seems to be caused by the URL not returning a json at the task run time. This change adds an additional check to the until condition to ensure the json is defined
```
TASK [wait-hosts-discovered : Wait up to 40 min for nodes to be discovered] ****
Wednesday 13 August 2025  08:59:42 +0000 (0:00:00.036)       0:00:35.599 ****** 
FAILED - RETRYING: [f19-h01-000-r640.rdu2.scalelab.redhat.com]: Wait up to 40 min for nodes to be discovered (40 retries left).
fatal: [f19-h01-000-r640.rdu2.scalelab.redhat.com]: FAILED! => {"msg": "The conditional check 'cluster.json.hosts | length == inventory_nodes | length' failed. The error was: error while evaluating conditional (cluster.json.hosts | length == …
```
> Fix wait for nodes to be discovered race condition

- ansible/roles/mno-scale-out-csr/tasks/main.yml
A scale-out deployment of two workers on a Compact MNO Cluster was attempted, but it did not work as expected. Although the playbook executed without any errors, the scale-out failed because the workers were not added to the cluster. It was discovered that the "Approve CSRs" task did not work as expected, and after examining the Ansible playbooks, it was realized that the way the worker node count was being filtered was incorrect.
After these changes were implemented, the workers were successfully scaled out in the Compact MNO cluster.
> Add scale out functionality for Compact MNO Cluster

- ansible/roles/bastion-network/tasks/main.yml
- ansible/roles/create-ai-cluster/tasks/static_network_config.yml
- ansible/roles/create-ai-cluster/templates/rhlab_bond_mac_interface_map.json.j2
- ansible/roles/create-ai-cluster/templates/rhlab_bond_nmstate.yml.j2
- ansible/roles/create-inventory/defaults/main/networks.yml
- ansible/roles/create-inventory/tasks/main.yml
- ansible/roles/create-inventory/templates/inventory-mno.j2
- ansible/roles/create-inventory/templates/inventory-sno.j2
- ansible/roles/validate-vars/tasks/main.yml
- ansible/vars/all.sample.yml
- docs/tips-and-vars.md
- Changes the bastion networking configuration as well
- Uses LACP mode (switch configuration required)
- Bonds first two interfaces (ports 0 & 1) for private network
- Reuses IBM Cloud terminology and structure for consistency
- Only applies to private VLAN scenarios in scale/perf labs
Assisted-by: Claude 🤖
> [PERFSCALE-3943] LACP bonding for perf/scale lab

- ansible/roles/bastion-install/tasks/main.yml
The current Ansible task for creating a symlink to the opm binary fails on RHEL with the error:
`TASK [bastion-install : Symlink RHEL9 opm] *************************************************************************************************************** Sunday 05 October 2025 03:28:31 -0400 (0:00:00.021) 0:00:31.244 ******** fatal: [10.26.8.107]: FAILED! => {"changed": false, "gid": 1000, "group": "jenkins", "mode": "0700", "msg": "refusing to convert from file to symlink for /usr/local/bin/opm", "owner": "jenkins", "path": "/usr/local/bin/opm", "secontext": "unconfined_u:object_r:bin_t:s0", "size": 81544080, "state": "file", "uid": 1000}`
This happens because a regular opm file already exists, and Ansible will not overwrite it unless explicitly instructed.
Added force: yes to the …
> Force replace old RHEL opm file

- ansible/roles/create-inventory/defaults/main/storage.yml
- ansible/roles/create-inventory/templates/inventory-mno.j2
- ansible/roles/create-inventory/templates/inventory-sno.j2
- ansible/vars/lab.yml
- Add hw_install_disk mapping table to ansible/vars/lab.yml with support for:
* Hardware defaults (e.g., r740xd)
* Rack-level overrides (e.g., y37-r740xd)
* Rack-unit-level overrides (e.g., y37-h01-r740xd)
- Update inventory templates to parse rack and rack-unit from hostnames and perform fallback lookup
- Remove hardcoded defaults from defaults/main/storage.yml
- Add support for user overrides via vars/all.yml that take precedence over hardware mappings
> Add hw_install_disk mapping for auto disk by path configuration
