redhat-performance/jetlag

ansible/roles/boot-iso/tasks/supermicro.yml
Updates:
- fixed typo of hostvars
- fixed iso format (path has to start with `\\`, host needs http & 8080)
- fixed bootoverridetarget (UsbCd->Usb)
=> update supermicro script

ansible/roles/sno-install-cluster/tasks/main.yml
=> Allows networktype for SNO

README.md, ansible/roles/bastion-assisted-installer/defaults/main.yml, ansible/roles/bastion-install/defaults/main.yml, ansible/roles/bastion-network/defaults/main/dns.yml, ansible/roles/bastion-network/defaults/main/networks.yml, ansible/roles/bm-post-cluster-install/defaults/main/storage.yml, ansible/roles/bm-post-cluster-install/tasks/main.yml, ansible/roles/create-ai-cluster/defaults/main/dns.yml, ansible/roles/create-ai-cluster/defaults/main/extras.yml, ansible/roles/create-ai-cluster/defaults/main/networks.yml, ansible/roles/create-inventory/defaults/main.yml, ansible/roles/generate-livecd/defaults/main.yml, ansible/roles/install-cluster/defaults/main/storage.yml, ansible/roles/rwn-post-cluster-install/defaults/main/rules.yml, ansible/roles/rwn-post-cluster-install/defaults/main/storage.yml, ansible/roles/rwn-post-cluster-install/tasks/main.yml, ansible/roles/sno-create-ai-cluster/defaults/main/dns.yml, ansible/roles/sno-create-ai-cluster/defaults/main/networks.yml, ansible/roles/sno-wait-hosts-discovered/defaults/main.yml, ansible/roles/wait-hosts-discovered/defaults/main/networks.yml, ansible/vars/all.sample.yml
Moved arbitrary variables in to default sections and simplified  all.yml for quick deploy. 
Test cases:
=> minimized mandatory inputs for AI

docs/troubleshooting.md
=> Add some additional troubleshooting docs regarding dell idrac and fixing

ansible/create-inventory.yml, ansible/roles/install-cluster/templates/install-config-overrides.yml.j2, ansible/roles/sno-install-cluster/tasks/main.yml, ansible/roles/validate-vars/tasks/main.yml, ansible/vars/all.sample.yml
=> Mix and match networktype for SNO

.github/workflows/ansible-lint.yml, ansible/inventory/inventory-bm.sample, ansible/inventory/inventory-rwn.sample, ansible/inventory/inventory-sno.sample, ansible/roles/create-inventory/templates/inventory-bm.j2, ansible/roles/create-inventory/templates/inventory-rwn.j2, ansible/roles/create-inventory/templates/inventory-sno.j2, ansible/setup-bastion.yml
=> Ensure bastion is powered on

ansible/vars/lab.yml
=> Update ALIAS foreman

README.md, docs/troubleshooting.md
=> Add clean disconnected registry container images to troubleshooting and

ansible/roles/install-cluster/defaults/main/main.yml, ansible/roles/install-cluster/tasks/check-cluster-install.yml
to avoid ansible recursion issue
=> Make the pause loop adjustable and increase the pause time period to 10s

ansible/roles/boot-iso/tasks/dell.yml
=> Power down machine prior to booting an iso for the Dell machines with an

ansible/roles/bm-post-cluster-install/defaults/main/main.yml, ansible/roles/bm-post-cluster-install/tasks/main.yml
=> Allow migrating the ingresscontrollers to the master nodes for

ansible/roles/install-cluster/defaults/main/main.yml, ansible/roles/sno-install-cluster/defaults/main.yml, ansible/roles/sno-post-cluster-install/tasks/main.yml
=> Add kubeburner sa for SNOs and adjust check period pause time for

ansible/vars/ibmcloud.sample.yml, docs/deploy-bm-ibmcloud.md, docs/troubleshooting.md
=> Add examples to the supermicro reset bmc and fix firewall interface

ansible/roles/install-cluster/defaults/main/main.yml, ansible/roles/install-cluster/tasks/check-cluster-install.yml
during installation in addition to machines that report installing-pending-user-action
=> Unmount virtual media from machines which report status as error

ansible/roles/bastion-assisted-installer/defaults/main/main.yml, ansible/roles/install-cluster/tasks/check-cluster-install.yml, ansible/roles/sno-install-cluster/tasks/check-single-sno-host.yml, ansible/roles/sno-install-cluster/tasks/check-sno-install.yml
Also reduce output using loop_control labels
=> Move to newer version of assisted-installer (v1.0.27.6)

README.md, ansible/vars/all.sample.yml
potentially mis-leading public network configuration from sample vars
file
=> Forgot to add r650s to tested Scale Lab hardware, also remove

ansible/roles/boot-iso/tasks/dell.yml, ansible/roles/install-cluster/tasks/check-cluster-install.yml, ansible/roles/install-cluster/tasks/dell-unmount-virtual-media.yml, ansible/roles/install-cluster/tasks/main.yml, ansible/roles/sno-install-cluster/tasks/check-single-sno-host.yml, ansible/roles/wait-hosts-discovered/tasks/main.yml
=> Make the dell boot iso routine more robust by being able to remove any

docs/tips-and-vars.md
Added steps to change the OCP version for cluster install
=> Steps to update the OCP version added to tips-and-vars.md

ansible/disconnected-sync-acm-d.yml, ansible/roles/bastion-disconnected-registry/defaults/main/main.yml, ansible/roles/disconnected-sync-acm-d/tasks/main.yml
Also set disconnected operators to v4.9
=> Changes to sync acm downstream into disconnected registry

ansible/roles/sno-post-cluster-install/defaults/main.yml, ansible/roles/sno-post-cluster-install/tasks/main.yml, ansible/roles/sno-post-cluster-install/templates/performance-addon-operator.yml.j2, docs/tips-and-vars.md
Added steps to Install Performance Addon Operator on SNOs and updated the documentation accordingly.
=> PAO install on SNOs

ansible/roles/disconnected-sync-acm-d/defaults/main/main.yml, ansible/roles/disconnected-sync-acm-d/tasks/main.yml, ansible/vars/disconnected-sync-acm-d.sample.yml
=> Enable syncing ACM and MCE container images for ACM 2.5 install in

ansible/hv-network-impairments.yml, ansible/roles/create-inventory/defaults/main/networks.yml, ansible/roles/create-inventory/templates/inventory-bm.j2, ansible/roles/create-inventory/templates/inventory-rwn.j2, ansible/vars/lab.yml, ansible/vars/network-impairments.sample.yml, docs/hypervisor-network-impairments.md
=> Enabling hv impairment playbook to work with multiple hypervisor

ansible/roles/wait-hosts-discovered/tasks/main.yml
=> Fix race condition while waiting for machines to be discovered

ansible/roles/bastion-gogs/tasks/main.yml, docs/tips-and-vars.md
=> Add a retry to "restarting" the gogs pod since it can execute too

ansible/roles/create-ai-cluster/tasks/01_manifest_update.yml, ansible/roles/ibmcloud-sno-create-ai-cluster/tasks/01_manifest_task.yml, ansible/roles/sno-create-ai-cluster/tasks/01_manifest_task.yml, ansible/roles/sno-post-cluster-install/defaults/main.yml, ansible/roles/sno-post-cluster-install/tasks/main.yml, ansible/roles/sno-post-cluster-install/templates/performance-profile.yml.j2, ansible/roles/validate-vars/tasks/main.yml, docs/tips-and-vars.md
Added performance-profile creation tasks for SNOs.
=> Post-install performance-profile tasks for SNOs

README.md, ansible/roles/bastion-install/tasks/main.yml
Very detailed Ansible installation instructions for virtualenv+pip for README.
=> Update README.md to include ansible install

bootstrap.sh
Install jmespath for sno deploy tasks
=> add install jmespath to bootstrap.sh

docs/deploy-bm-quickstart.md
Added a few bits at the end to interact with the cluster.
=> FIX documentation for the bm installation

docs/troubleshooting.md
I have updated troubleshooting in case of missing administrator privileges for IPMI and also when its too low.
=> Update troubleshooting error

README.md, docs/deploy-bm-quickstart.md, docs/deploy-sno-quickstart.md
SNO install with Supermicro 1029U required little fixes and a small update to the documentation.
=> Small fixes to the documentation while installing an SNO in a Supermicro

ansible/roles/bastion-disconnected-registry/tasks/main.yml, ansible/roles/bastion-install/tasks/main.yml
=> Add support-tools to the disconnected registry and install rsync for

ansible/roles/create-inventory/templates/inventory-sno.j2, ansible/roles/sno-create-ai-cluster/defaults/main/bastion-disconnected-registry.yml, ansible/roles/sno-create-ai-cluster/tasks/main.yml, ansible/roles/sno-generate-discovery-iso/defaults/main/bastion-disconnected-registry.yml, ansible/roles/sno-generate-discovery-iso/tasks/main.yml, ansible/roles/sno-generate-discovery-iso/templates/disconnected-discovery.ign.j2, ansible/roles/sno-generate-discovery-iso/templates/nmstate.yml.j2, ansible/roles/sno-generate-discovery-iso/templates/registries.conf.j2, ansible/roles/sno-install-cluster/defaults/main/bastion-disconnected-registry.yml, ansible/roles/sno-install-cluster/tasks/main.yml, ansible/roles/sno-install-cluster/templates/install-config-overrides.yml.j2, ansible/roles/sno-wait-hosts-discovered/tasks/main.yml, docs/deploy-sno-quickstart.md, docs/troubleshooting.md
The series of changes in this patch enables SNO with IPv6 in jetlag.
=> Enabling SNO with IPv6

ansible/roles/bastion-http/templates/httpd.conf
=> Allow httpd to show full file names in directory listing for easier

ansible/roles/hv-vm-manifests-sno/defaults/main.yml, ansible/roles/hv-vm-manifests-sno/templates/siteconfig.yml.j2, ansible/vars/disconnected-sync-acm-d.sample.yml
=> Add ironic inspect option to siteconfigs for ACM ZTP of SNOs with

ansible/roles/bastion-gogs/tasks/main.yml
=> fix: Attempt to set proper podman network

ansible/hv-vm-create.yml, ansible/hv-vm-replace.yml, ansible/roles/hv-vm-manifests-compact/templates/siteconfig-resources.yml.j2, ansible/roles/hv-vm-manifests-compact/templates/siteconfig.yml.j2, ansible/roles/hv-vm-manifests-standard/templates/siteconfig-resources.yml.j2, ansible/roles/hv-vm-manifests-standard/templates/siteconfig.yml.j2, ansible/vars/hv.sample.yml
=> Allow mixed cluster manifests to be produced from create/replace vm

docs/troubleshooting.md
@Noreen21 @akrzos : I have added some of notes here to the boot mode, order and a few other things based on the ALIAS experience. Please, have a look if there are gaps or things to be improved.
=> Some troubleshooting additions based on the ALIAS experience

ansible/roles/install-cluster/templates/controlplane-setup-lvm.sh.j2, ansible/roles/install-cluster/templates/worker-setup-lvm.sh.j2
=> Slight change for pvremove to work with by-path for localstorage device

ansible/roles/bastion-http/tasks/main.yml
Fixes: https://github.com/redhat-performance/jetlag/issues/355
=> Use quay for centos registry

docs/tips-and-vars.md
Adds section:
Configuring NVMe install and etcd disks
=> Add tip on nvme and disk/by-path

ansible/roles/create-ai-cluster/templates/08-set-rcu-normal-master.yaml, ansible/roles/sno-create-ai-cluster/tasks/01_manifest_task.yml, ansible/roles/sno-install-cluster/templates/install-config-overrides.yml.j2, ansible/roles/sno-install-cluster/templates/sno-setup-lvm.sh.j2, ansible/roles/sno-post-cluster-install/tasks/main.yml, ansible/roles/sno-post-cluster-install/templates/ReduceMonitoringFootprint.yml.j2, ansible/roles/sno-post-cluster-install/templates/performance-profile.yml.j2, ansible/roles/sno-post-cluster-install/templates/tunedPerformancePatch.yml.j2
1. Added DU profile changes for OCP 4.14
2. Updated sno lvm setup stript to match regular cluster install lvm setup script
=> sno lvm setup and 4.14 du updates

ansible/roles/bastion-ocp-version/tasks/main.yml
=> Prevent existing kubeconfig from preventing setup bastion working correctly

ansible/roles/hv-vm-manifests-compact/defaults/main.yml, ansible/roles/hv-vm-manifests-compact/templates/siteconfig.yml.j2, ansible/roles/hv-vm-manifests-sno/defaults/main.yml, ansible/roles/hv-vm-manifests-sno/templates/siteconfig.yml.j2, ansible/roles/hv-vm-manifests-standard/defaults/main.yml, ansible/roles/hv-vm-manifests-standard/templates/siteconfig.yml.j2
=> Add option to exclude ztp manifest to sync chronyd once via

ansible/roles/sno-create-ai-cluster/tasks/01_manifest_task.yml, ansible/roles/sno-install-cluster/templates/install-config-overrides.yml.j2, ansible/roles/sno-post-cluster-install/tasks/main.yml
4.14 workload partitioning updates
=> sno du 4.14 updates

ansible/roles/hv-vm-manifests-compact/defaults/main.yml, ansible/roles/hv-vm-manifests-compact/templates/siteconfig-resources.yml.j2, ansible/roles/hv-vm-manifests-compact/templates/siteconfig.yml.j2, ansible/roles/hv-vm-manifests-sno/defaults/main.yml, ansible/roles/hv-vm-manifests-sno/templates/siteconfig-resources.yml.j2, ansible/roles/hv-vm-manifests-sno/templates/siteconfig.yml.j2, ansible/roles/hv-vm-manifests-standard/defaults/main.yml, ansible/roles/hv-vm-manifests-standard/templates/siteconfig-resources.yml.j2, ansible/roles/hv-vm-manifests-standard/templates/siteconfig.yml.j2
data or in the siteconfig resources yaml
=> Add option to create a configmap per siteconfig in either siteconfigmap

ansible/roles/hv-vm-manifests-compact/templates/siteconfig.yml.j2, ansible/roles/hv-vm-manifests-sno/templates/siteconfig.yml.j2, ansible/roles/hv-vm-manifests-standard/templates/siteconfig.yml.j2
=> Adjust siteconfig to v2 api when using siteConfigMap and use the

README.md, docs/tips-and-vars.md
Update README.md
Add additional info to by-path tips
=> Supermicro 1029U cluster installed

ansible/roles/bastion-http/tasks/main.yml
=> update httpd component tag

docs/bastion-deploy-bm.md, docs/tips-and-vars.md
Added extra vars which are useful for overcoming the symbolic link issues.
=> added extra vars for disks in docs

ansible.cfg, ansible/roles/sync-operator-index/defaults/main.yml, ansible/roles/sync-operator-index/tasks/main.yml, ansible/vars/sync-operator-index.sample.yml
brew registry after rendering the operator declarative config in the index image
=> Add support to sync brew operators by replacing the registry with the

ansible/roles/create-ai-cluster/templates/99-sync-time-once-master.yaml, ansible/roles/sno-create-ai-cluster/tasks/01_manifest_task.yml, ansible/roles/sno-install-cluster/templates/install-config-overrides.yml.j2, ansible/roles/sno-post-cluster-install/templates/performance-profile.yml.j2, ansible/roles/sno-post-cluster-install/templates/tunedPerformancePatch.yml.j2
1. Added updates for ocp 4.16
2. Added previously missing 99-sync-time-once-master.yaml
Refer to [source-crs](https://github.com/openshift-kni/cnf-features-deploy/tree/master/ztp/source-crs) for details.
=> du profile updates

ansible/vars/all.sample.yml, docs/bastion-deploy-bm-byol.md, docs/bastion-deploy-bm.md, docs/deploy-sno-quickstart.md
=> Move `public_vlan` var lower because it isn't as important and will

ansible/roles/bastion-install/tasks/main.yml
Closes https://github.com/redhat-performance/jetlag/issues/526
=> Hardcode opm cli url for rhel8

ansible/roles/hv-dnsmasq/templates/jetlag.conf.j2, ansible/roles/hv-vm-manifests-sno/templates/siteconfig.yml.j2
- current template for siteconfig assumed ipv6
- Fix the dnsmasq config so it listens on the right interface
=> Fixes for ipv4 and dnsmasq

ansible/roles/hv-vm-manifests-sno/defaults/main.yml, ansible/roles/hv-vm-manifests-sno/templates/siteconfig.yml.j2
=> Add each du profile version of installConfigOverrides such that

ansible/roles/bm-post-cluster-install/defaults/main/main.yml, ansible/roles/bm-post-cluster-install/tasks/main.yml, ansible/roles/bm-post-cluster-install/templates/openshift-gitops-operator.yml.j2
for ZTP via manual install approval process.
=> Remove no longer used method to install a specific version of gitops

ansible/roles/bm-post-cluster-install/defaults/main/main.yml, ansible/roles/bm-post-cluster-install/tasks/main.yml, docs/bastion-deploy-bm.md, docs/deploy-sno-quickstart.md
=> Remove `fix_metal3_provisioningosdownloadurl` due to usage only in much

ansible/roles/create-inventory/tasks/main.yml
Updating to point to the right URL
=> Quads changed the URL for the inventory

README.md, docs/tips-and-vars.md
Used jetlag on scale lab to install an sno and bm cluster on r660 instances.
=> Tested sno and bm installation on r660 instances.

ansible/roles/create-inventory/tasks/main.yml
Adding pipefail to the vlan retrieval command will help on debugging.
=> Adding pipefail to command

ansible/roles/bastion-install/tasks/main.yml
iptables is nft based in RHEL9, just need to pull in the right package to make sure things work the same.
=> support a RHEL9 bastion

ansible/roles/bastion-assisted-installer/defaults/main/main.yml
bumping the version to fix 4.19 deploys
=> Update the ai-service version

ansible/roles/hv-vm-create/defaults/main.yml, ansible/roles/hv-vm-create/tasks/main.yml, ansible/roles/hv-vm-create/templates/kvm-def.xml.j2, docs/hypervisors.md
Added vNUMA configuration support for VMs
=> vnuma config for VMs

ansible/roles/generate-discovery-iso/tasks/main.yml
Add Download discovery ISO task retries
Closes https://github.com/redhat-performance/jetlag/issues/674
=> Add Download discovery ISO task retries

ansible/roles/create-inventory/tasks/main.yml, ansible/roles/create-inventory/templates/inventory-mno.j2, ansible/roles/create-inventory/templates/inventory-sno.j2, ansible/roles/create-inventory/templates/inventory-vmno.j2, ansible/vars/all.sample.yml, docs/tips-and-vars.md
Closes https://github.com/redhat-performance/jetlag/issues/678
=> PERFSCALE-4093: Auto configure network interfaces vars

ansible/roles/create-ai-cluster/templates/rhlab_nmstate.yml.j2
Fixes [PR#691](https://github.com/redhat-performance/jetlag/issues/691)
=> Configure ingress secondary address on SNO cluster
